[package]
name = "ruvoraq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "A modular Rust backend framework with typed APIs and automatic OpenAPI documentation"
publish = ["crates-io"]
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["ruvoraq", "backend", "web", "api"]
categories = ["web-programming::http-server", "development-tools"]

[features]
default = []
sqlite = ["dep:ruvoraq-db", "ruvoraq-db/sqlite"]
postgres = ["dep:ruvoraq-db", "ruvoraq-db/postgres"]

[dependencies]
ruvoraq-db = { version = "0.1.0", path = "../ruvoraq-db", optional = true, default-features = false }
ruvoraq-config = { version = "0.1.0", path = "../ruvoraq-config" }
ruvoraq-web = { version = "0.1.0", path = "../ruvoraq-web" }
ruvoraq-macros = { version = "0.1.0", path = "../ruvoraq-macros" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
axum.workspace = true
tower.workspace = true
tokio = { workspace = true, features = ["macros", "io-util", "sync", "time"] }
