[package]
name = "ruvoraq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Ruvoraq public API"
publish = false

[features]
default = []
sqlite = ["dep:ruvoraq-db"]

[dependencies]
ruvoraq-db = { path = "../ruvoraq-db", optional = true }
ruvoraq-config = { path = "../ruvoraq-config" }
ruvoraq-web = { path = "../ruvoraq-web" }
ruvoraq-macros = { path = "../ruvoraq-macros" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
axum.workspace = true
tower.workspace = true
tokio = { workspace = true, features = ["macros", "io-util", "sync", "time"] }
