#![cfg(feature = "postgres")]
use ruvoraq_db::{Migrations, PostgresDatabase, sqlx};
use std::{
    fs,
    path::PathBuf,
    sync::atomic::{AtomicU64, Ordering},
};
static NEXT: AtomicU64 = AtomicU64::new(0);

struct Files(PathBuf);
impl Files {
    fn new() -> Self {
        let path = std::env::temp_dir().join(format!(
            "ruvoraq-pg-files-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir(&path).unwrap();
        Self(path)
    }
    fn write(&self, name: &str, sql: &str) {
        fs::write(self.0.join(name), sql).unwrap();
    }
}
impl Drop for Files {
    fn drop(&mut self) {
        fs::remove_dir_all(&self.0).unwrap();
    }
}

struct Fixture {
    admin: sqlx::PgPool,
    database: PostgresDatabase,
    schema: String,
    url: String,
}
impl Fixture {
    async fn new() -> Self {
        let base = std::env::var("RUVORAQ_TEST_POSTGRES_URL")
            .expect("set a dedicated RUVORAQ_TEST_POSTGRES_URL");
        let admin = sqlx::postgres::PgPoolOptions::new()
            .max_connections(1)
            .connect(&base)
            .await
            .unwrap();
        let schema = format!(
            "ruvoraq_test_{}_{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        );
        sqlx::query(&format!("CREATE SCHEMA {schema}"))
            .execute(&admin)
            .await
            .unwrap();
        let separator = if base.contains('?') { '&' } else { '?' };
        let url = format!("{base}{separator}options=-csearch_path%3D{schema}");
        let database = PostgresDatabase::connect(&url).await.unwrap();
        Self {
            admin,
            database,
            schema,
            url,
        }
    }
    async fn close(self) {
        self.database.close().await;
        // The identifier was generated by this fixture; no application schema is dropped.
        sqlx::query(&format!("DROP SCHEMA {} CASCADE", self.schema))
            .execute(&self.admin)
            .await
            .unwrap();
        self.admin.close().await;
    }
}
async fn exists(db: &PostgresDatabase, table: &str) -> bool {
    let (present,): (bool,) = sqlx::query_as("SELECT to_regclass($1) IS NOT NULL")
        .bind(table)
        .fetch_one(db.pool())
        .await
        .unwrap();
    present
}

#[tokio::test]
async fn wrong_schemes_and_invalid_urls_are_redacted() {
    for url in [
        "sqlite::memory:",
        "mysql://private-secret",
        "postgres://user:private-secret@localhost:invalid/db",
    ] {
        let error = PostgresDatabase::connect(url)
            .await
            .unwrap_err()
            .to_string();
        assert!(!error.contains("private-secret"));
        assert!(error.contains("DATABASE_URL"));
    }
}

#[tokio::test]
#[ignore = "requires dedicated RUVORAQ_TEST_POSTGRES_URL"]
async fn real_postgres_binding_transactions_foreign_keys_and_reconnect() {
    let fixture = Fixture::new().await;
    let db = &fixture.database;
    sqlx::query("CREATE TABLE notes (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, title TEXT NOT NULL)")
        .execute(db.pool()).await.unwrap();
    let title = "'); DROP TABLE notes; --";
    let (id,): (i64,) = sqlx::query_as("INSERT INTO notes (title) VALUES ($1) RETURNING id")
        .bind(title)
        .fetch_one(db.pool())
        .await
        .unwrap();
    let mut tx = db.begin().await.unwrap();
    sqlx::query("INSERT INTO notes (title) VALUES ($1)")
        .bind("committed")
        .execute(&mut *tx)
        .await
        .unwrap();
    tx.commit().await.unwrap();
    let mut tx = db.begin().await.unwrap();
    sqlx::query("INSERT INTO notes (title) VALUES ($1)")
        .bind("rolled back")
        .execute(&mut *tx)
        .await
        .unwrap();
    tx.rollback().await.unwrap();
    let mut tx = db.begin().await.unwrap();
    sqlx::query("INSERT INTO notes (title) VALUES ($1)")
        .bind("dropped")
        .execute(&mut *tx)
        .await
        .unwrap();
    drop(tx);
    let clone = db.clone();
    let (count,): (i64,) = sqlx::query_as("SELECT COUNT(*) FROM notes")
        .fetch_one(clone.pool())
        .await
        .unwrap();
    assert_eq!(count, 2);
    sqlx::raw_sql("CREATE TABLE parents (id BIGINT PRIMARY KEY); CREATE TABLE children (parent_id BIGINT REFERENCES parents(id));")
        .execute(db.pool()).await.unwrap();
    assert!(
        sqlx::query("INSERT INTO children VALUES (99)")
            .execute(db.pool())
            .await
            .is_err()
    );
    let debug = format!("{db:?}");
    assert!(!debug.contains("postgres://") && !debug.contains(&fixture.url));
    db.close().await;
    let reopened = PostgresDatabase::connect(&fixture.url).await.unwrap();
    let row: (String,) = sqlx::query_as("SELECT title FROM notes WHERE id=$1")
        .bind(id)
        .fetch_one(reopened.pool())
        .await
        .unwrap();
    assert_eq!(row.0, title);
    reopened.close().await;
    fixture.close().await;
}

#[tokio::test]
#[ignore = "requires dedicated RUVORAQ_TEST_POSTGRES_URL"]
async fn real_postgres_migration_history_failures_and_recovery() {
    let fixture = Fixture::new().await;
    let db = &fixture.database;
    let files = Files::new();
    let first = "CREATE TABLE notes (title TEXT NOT NULL); INSERT INTO notes VALUES ('original');";
    files.write("1_notes.sql", first);
    assert!(!db.migration_status(&files.0).await.unwrap()[0].applied);
    assert!(!exists(db, "_sqlx_migrations").await);
    assert_eq!(db.migrate(&files.0).await.unwrap(), 1);
    assert_eq!(db.migrate(&files.0).await.unwrap(), 0);
    files.write("2_failure.sql","CREATE TABLE transient (id BIGINT); INSERT INTO notes VALUES ('temporary'); INSERT INTO private_secret_missing_table VALUES (1);");
    let error = db.migrate(&files.0).await.unwrap_err().to_string();
    assert!(error.contains("migration 2 failed") && !error.contains("private_secret"));
    assert!(!exists(db, "transient").await);
    let (count,): (i64,) = sqlx::query_as("SELECT COUNT(*) FROM notes")
        .fetch_one(db.pool())
        .await
        .unwrap();
    assert_eq!(count, 1);
    files.write(
        "2_failure.sql",
        "CREATE INDEX notes_title_index ON notes(title);",
    );
    assert_eq!(db.migrate(&files.0).await.unwrap(), 1);
    files.write(
        "3_pending.sql",
        "CREATE TABLE should_not_exist (id BIGINT);",
    );
    files.write("1_notes.sql", &format!("{first}\n-- changed"));
    assert!(
        db.migrate(&files.0)
            .await
            .unwrap_err()
            .to_string()
            .contains("has changed")
    );
    assert!(!exists(db, "should_not_exist").await);
    fs::remove_file(files.0.join("1_notes.sql")).unwrap();
    assert!(
        db.migration_status(&files.0)
            .await
            .unwrap_err()
            .to_string()
            .contains("missing")
    );
    files.write("1_notes.sql", first);
    assert_eq!(db.migrate(&files.0).await.unwrap(), 1);
    sqlx::query("UPDATE _sqlx_migrations SET success=false WHERE version=1")
        .execute(db.pool())
        .await
        .unwrap();
    assert!(
        db.migrate(&files.0)
            .await
            .unwrap_err()
            .to_string()
            .contains("incomplete")
    );
    fixture.close().await;
}

#[tokio::test]
#[ignore = "requires dedicated RUVORAQ_TEST_POSTGRES_URL"]
async fn real_postgres_concurrent_migrators_share_an_advisory_lock() {
    let fixture = Fixture::new().await;
    let second = PostgresDatabase::connect(&fixture.url).await.unwrap();
    let files = Files::new();
    files.write(
        "1_notes.sql",
        "SELECT pg_sleep(0.1); CREATE TABLE notes (title TEXT); INSERT INTO notes VALUES ('once');",
    );
    let migrations = Migrations::load(&files.0).await.unwrap();
    let (first, second_result) = tokio::join!(
        migrations.run_postgres(&fixture.database),
        migrations.run_postgres(&second)
    );
    let mut counts = vec![first.unwrap(), second_result.unwrap()];
    counts.sort();
    assert_eq!(counts, vec![0, 1]);
    let (count,): (i64,) = sqlx::query_as("SELECT COUNT(*) FROM notes")
        .fetch_one(second.pool())
        .await
        .unwrap();
    assert_eq!(count, 1);
    second.close().await;
    fixture.close().await;
}

#[tokio::test]
#[ignore = "requires dedicated RUVORAQ_TEST_POSTGRES_URL"]
async fn real_postgres_connection_failures_and_required_tls_are_redacted() {
    let base = std::env::var("RUVORAQ_TEST_POSTGRES_URL").unwrap();
    let url = base.replace("/ruvoraq_test", "/missing_private_secret_database");
    let error = PostgresDatabase::connect(&url)
        .await
        .unwrap_err()
        .to_string();
    assert!(!error.contains("private_secret") && !error.contains(&base));
    let separator = if base.contains('?') { '&' } else { '?' };
    let error = PostgresDatabase::connect(&format!("{base}{separator}sslmode=require"))
        .await
        .unwrap_err()
        .to_string();
    assert!(!error.contains(&base));
    assert!(error.contains("cannot connect to PostgreSQL"));
}

#[tokio::test]
#[ignore = "requires dedicated RUVORAQ_TEST_POSTGRES_URL"]
async fn real_postgres_post_commit_bookkeeping_failure_preserves_history_and_unlocks() {
    let fixture = Fixture::new().await;
    let files = Files::new();
    files.write("1_notes.sql", "CREATE TABLE notes (title TEXT);");
    fixture.database.migrate(&files.0).await.unwrap();
    sqlx::raw_sql(
        "CREATE FUNCTION reject_migration_timing() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'private_bookkeeping_error'; END $$;
         CREATE TRIGGER reject_migration_timing BEFORE UPDATE ON _sqlx_migrations FOR EACH ROW EXECUTE FUNCTION reject_migration_timing();")
        .execute(fixture.database.pool()).await.unwrap();
    files.write("2_committed.sql", "INSERT INTO notes VALUES ('committed');");
    let error = fixture
        .database
        .migrate(&files.0)
        .await
        .unwrap_err()
        .to_string();
    assert!(error.contains("inspect database history"));
    assert!(!error.contains("rolled back") && !error.contains("private_bookkeeping"));
    let (count,): (i64,) = sqlx::query_as("SELECT COUNT(*) FROM notes")
        .fetch_one(fixture.database.pool())
        .await
        .unwrap();
    assert_eq!(count, 1);
    assert!(
        fixture
            .database
            .migration_status(&files.0)
            .await
            .unwrap()
            .iter()
            .all(|s| s.applied)
    );
    // Retrying skips the committed file, and the failed runner released its lock.
    assert_eq!(fixture.database.migrate(&files.0).await.unwrap(), 0);
    fixture.close().await;
}
