[package]
name = "ruvoraq-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Create, organize, run and migrate Ruvoraq Rust backend applications"
publish = ["crates-io"]
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["ruvoraq", "backend", "web", "api"]
categories = ["web-programming::http-server", "development-tools"]

[[bin]]
name = "ruvoraq"
path = "src/main.rs"
doc = false

[features]
default = []
postgres = ["ruvoraq-db/postgres"]

[dependencies]
toml.workspace = true
syn.workspace = true
ruvoraq-config = { version = "0.2.0", path = "../ruvoraq-config" }
ruvoraq-db = { version = "0.2.0", path = "../ruvoraq-db" }
tokio.workspace = true
